const state={theme:'light',data:[
{date:'2026-06-03',department:'Grocery',product:'Rice 5kg',units:12,sales:15600,cost:12480,profit:3120,paymentMode:'UPI',stockLeft:24,stockStatus:'Low',remarks:'High demand'},
{date:'2026-06-03',department:'Dairy',product:'Milk Pack',units:30,sales:9000,cost:6300,profit:2700,paymentMode:'Cash',stockLeft:52,stockStatus:'Healthy',remarks:''},
{date:'2026-06-04',department:'Snacks',product:'Namkeen Pack',units:24,sales:6000,cost:3840,profit:2160,paymentMode:'Card',stockLeft:18,stockStatus:'Low',remarks:''},
{date:'2026-06-04',department:'Personal Care',product:'Soap Combo',units:16,sales:3200,cost:2080,profit:1120,paymentMode:'UPI',stockLeft:40,stockStatus:'Healthy',remarks:''}
],filters:{date:'2026-06-04',department:'all',paymentMode:'all',stockStatus:'all'}};
const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const loginView=document.getElementById('loginView'),appView=document.getElementById('appView'),pageEls=[...document.querySelectorAll('.page')],navBtns=[...document.querySelectorAll('.nav')],fileInput=document.getElementById('fileInput'),uploadStatus=document.getElementById('uploadStatus');
let deptChart,payChart;

function filtered(){return state.data.filter(r=>(!state.filters.date||r.date===state.filters.date)&&(state.filters.department==='all'||r.department===state.filters.department)&&(state.filters.paymentMode==='all'||r.paymentMode===state.filters.paymentMode)&&(state.filters.stockStatus==='all'||r.stockStatus===state.filters.stockStatus));}
function aggDept(data){return Object.values(data.reduce((a,r)=>(a[r.department]??={department:r.department,sales:0,profit:0,units:0},a[r.department].sales+=r.sales,a[r.department].profit+=r.profit,a[r.department].units+=r.units,a),{})).sort((a,b)=>b.sales-a.sales);}
function render(){const data=filtered();document.getElementById('kpiSales').textContent=money.format(data.reduce((s,r)=>s+r.sales,0));document.getElementById('kpiProfit').textContent=money.format(data.reduce((s,r)=>s+r.profit,0));document.getElementById('kpiUnits').textContent=data.reduce((s,r)=>s+r.units,0).toLocaleString('en-IN');document.getElementById('kpiLow').textContent=data.filter(r=>r.stockStatus==='Low').length;document.getElementById('recordBody').innerHTML=data.map(r=>`<tr><td>${r.date}</td><td>${r.department}</td><td>${r.product}</td><td>${r.units}</td><td>${money.format(r.sales)}</td><td>${money.format(r.profit)}</td><td>${r.stockStatus}</td><td>${r.paymentMode}</td></tr>`).join('')||'<tr><td colspan="8">No records</td></tr>';document.getElementById('alertBox').innerHTML=data.filter(r=>r.stockStatus==='Low').map(r=>`<div class="alert"><strong>${r.product}</strong><div>${r.department} stock is low (${r.stockLeft} left)</div></div>`).join('')||'<div class="alert">No urgent alerts</div>';document.getElementById('summaryBody').innerHTML=aggDept(state.data).map(r=>`<tr><td>${r.department}</td><td>${money.format(r.sales)}</td><td>${money.format(r.profit)}</td><td>${r.units}</td></tr>`).join('');if(deptChart){const ad=aggDept(data);deptChart.data.labels=ad.map(r=>r.department);deptChart.data.datasets[0].data=ad.map(r=>r.sales);deptChart.update();const pay={Cash:0,UPI:0,Card:0};data.forEach(r=>pay[r.paymentMode]+=r.sales);payChart.data.datasets[0].data=[pay.Cash,pay.UPI,pay.Card];payChart.update();}}
function setPage(id){pageEls.forEach(p=>p.classList.toggle('active',p.id===id));navBtns.forEach(b=>b.classList.toggle('active',b.dataset.page===id));const map={dashboard:['Daily store analytics','Upload your Excel file every day to generate analytics instantly.'],upload:['Upload Excel','Use the Excel template and keep the headers unchanged.'],manual:['Manual entry','Use this for quick corrections or single records.'],reports:['Reports','Review summary and export the dataset.']};document.getElementById('title').textContent=map[id][0];document.getElementById('subtitle').textContent=map[id][1];}
function initCharts(){deptChart=new Chart(document.getElementById('deptChart'),{type:'bar',data:{labels:[],datasets:[{label:'Sales',data:[],backgroundColor:'#0b6a6f'}]},options:{plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{grid:{color:'rgba(0,0,0,.08)'}}}}});payChart=new Chart(document.getElementById('payChart'),{type:'doughnut',data:{labels:['Cash','UPI','Card'],datasets:[{data:[0,0,0],backgroundColor:['#0b6a6f','#d19a00','#006494']}]},options:{}});}
function exportCsv(){const h=['date','department','product','units','sales','cost','profit','paymentMode','stockLeft','stockStatus','remarks'];const rows=state.data.map(r=>h.map(k=>JSON.stringify(r[k]??'')).join(','));const blob=new Blob([[h.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='retailflow_export.csv';a.click();}
function parseFile(file){uploadStatus.textContent=`Loading ${file.name}...`;const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(new Uint8Array(e.target.result),{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});if(!rows.length){alert('Empty file');return;}const req=['date','department','product','units','unit_price','cost_per_unit','payment_mode','stock_left'];const miss=req.filter(c=>!(c in rows[0]));if(miss.length){alert('Missing columns: '+miss.join(', '));return;}const incoming=rows.map(r=>{const u=Number(r.units||1),sp=Number(r.unit_price||100),cp=Number(r.cost_per_unit||70),sl=Number(r.stock_left||50);return{date:r.date,department:r.department,product:r.product,units:u,sales:u*sp,cost:u*cp,profit:(u*sp)-(u*cp),paymentMode:r.payment_mode||'Cash',stockLeft:sl,stockStatus:sl<=25?'Low':'Healthy',remarks:r.remarks||''};}).filter(r=>r.date&&r.department&&r.product);state.data=[...incoming,...state.data];state.filters.date=incoming[0]?.date||state.filters.date;document.getElementById('saleDate').value=state.filters.date;uploadStatus.textContent=`Imported ${incoming.length} rows from ${file.name}`;render();alert('Excel/CSV imported successfully');}catch(err){alert('Failed to read file: '+err.message);}};reader.readAsArrayBuffer(file);}
document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();if(loginEmail.value.trim()==='manager@retailflow.com'&&loginPassword.value.trim()==='mca123'){loginView.classList.add('hidden');appView.classList.remove('hidden');render();}else alert('Invalid demo login');});
document.getElementById('logoutBtn').addEventListener('click',()=>{appView.classList.add('hidden');loginView.classList.remove('hidden');});
document.getElementById('themeBtn').addEventListener('click',()=>{state.theme=state.theme==='light'?'dark':'light';document.documentElement.setAttribute('data-theme',state.theme);render();});
document.getElementById('uploadBtn').addEventListener('click',()=>fileInput.click());
document.getElementById('chooseFileBtn').addEventListener('click',()=>fileInput.click());
fileInput.addEventListener('change',e=>{if(e.target.files[0])parseFile(e.target.files[0]);});
document.getElementById('dashboard').addEventListener('dragover',e=>e.preventDefault());
document.getElementById('dashboard').addEventListener('drop',e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)parseFile(f);});
document.getElementById('salesForm').addEventListener('submit',e=>{e.preventDefault();const u=Number(units.value),sp=Number(price.value),cp=Number(cost.value),sl=Number(stock.value);state.data.unshift({date:saleDate.value,department:dept.value,product:product.value,units:u,sales:u*sp,cost:u*cp,profit:(u*sp)-(u*cp),paymentMode:mode.value,stockLeft:sl,stockStatus:sl<=25?'Low':'Healthy',remarks:remarks.value});render();setPage('dashboard');});
document.getElementById('exportBtn').addEventListener('click',exportCsv);
navBtns.forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));
setPage('dashboard');document.getElementById('saleDate').value='2026-06-04';initCharts();render();